# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
