# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_profiles_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
