# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 03:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_profiles_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='friends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
