# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_auto_20171006_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, default='Your profile here', max_length=420),
        ),
    ]
