# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20171007_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='bio',
            field=models.CharField(blank=True, default='Hello, Grumblr!', max_length=420),
        ),
    ]
