# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20171007_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='last_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
