# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_posts_last_change'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='last_change',
            new_name='last_changed',
        ),
    ]
